language: node_js
node_js:
  - "7"
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST
notifications:
    email:
        recipients:
            - ta7382@gmail.com
        on_success: always
        on_failure: always
install:
    - npm install
script:
    - npm test
