language: node_js
node_js:
  - "8"
notifications:
    email:
        recipients:
            - ta7382@gmail.com
        on_success: always
        on_failure: always
install:
    - cd lib
    - npm install
script:
    - npm start
