language: node_js
node_js:
  - "10"
notifications:
    email:
        recipients:
            - ta7382@gmail.com
        on_failure: always
install:
    - cd lib
    - npm install
script:
    - npm start
